#!/bin/bash

git clone https://github.com/improbable-eng/grpc-web.git $GOPATH/src/github.com/improbable-eng/grpc-web
cd $GOPATH/src/github.com/improbable-eng/grpc-web/go/grpcwebproxy
go mod init grpcwebproxy && go mod tidy
go install .
